### ISSUE TITLE
无法成功下载数据集

### ISSUE THREAD

**Issue by zelo2** [tswsxk/EduData#8]
## 🐛 Description
edudata download assistment-2009-2010-skill 报错，以及后续许多数据集下载时候404错误，无法访问。
请问链接：http://base.ustc.edu.cn/data/cdbd/ 是必须学校的网才能访问么？校外404报错。

### Error Message
Traceback (most recent call last):
  File "e:\anaconda\envs\pytorch\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\anaconda\envs\pytorch\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda\envs\pytorch\Scripts\edudata.exe\__main__.py", line 7, in <module>
  File "e:\anaconda\envs\pytorch\lib\site-packages\EduData\main.py", line 47, in cli
    "sim": similarity_graph,
  File "e:\anaconda\envs\pytorch\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "e:\anaconda\envs\pytorch\lib\site-packages\fire\core.py", line 468, in _Fire
    target=component.__name__)
  File "e:\anaconda\envs\pytorch\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "e:\anaconda\envs\pytorch\lib\site-packages\EduData\DataSet\download_data\download_data.py", line 224, in get_data
    return download_data(url, data_dir, override)
  File "e:\anaconda\envs\pytorch\lib\site-packages\EduData\DataSet\download_data\download_data.py", line 187, in download_data
    download_file(url, save_path, override)
  File "e:\anaconda\envs\pytorch\lib\site-packages\EduData\DataSet\download_data\download_data.py", line 158, in download_file
    decompress(save_path)
  File "e:\anaconda\envs\pytorch\lib\site-packages\EduData\DataSet\download_data\utils.py", line 14, in decompress
    un_zip(file)
  File "e:\anaconda\envs\pytorch\lib\site-packages\EduData\DataSet\download_data\utils.py", line 29, in un_zip
    zip_file = zipfile.ZipFile(file)
  File "e:\anaconda\envs\pytorch\lib\zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "e:\anaconda\envs\pytorch\lib\zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Operating System: win10

**Python Version:** (anaconda/python3.7)

**Comment by tswsxk** [comment]
数据存储网站出现了宕机，目前已经修复，可以正常下载
